### ISSUE TITLE
[Feature] Provision for multiple instances of ETCD through ETCD CRD

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#129]
**Feature (What you would like to be added):** ETCD druid should create multiple ETCD instances(along with ETCDBR instances) as specified in ETCD CRD.

**Motivation (Why is this needed?):** To allow bootstrapping of multinode ETCD cluster for shoot cluster

**Approach/Hint to the implement solution (optional):** 

Refer: https://github.com/gardener/etcd-druid/issues/107

**Comment by amshuman-kr** [comment]
@abdasgupta Does it make sense to close this issue in favour of the issues listed here -> https://github.com/gardener/etcd-druid/issues/107? I have tried to keep the scope for those issues specific and with links to the relevant sections in the proposal.

**Comment by abdasgupta** [comment]
@amshuman-kr  Yes, go ahead please

**Comment by amshuman-kr** [comment]
Thanks.

/close In favour or https://github.com/gardener/etcd-druid/issues/158
