### ISSUE TITLE
[Feature] Automated gardener integration tests

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#134]
**Feature (What you would like to be added):**

We should created a suite of automated tests that test gardener integration.

**Motivation (Why is this needed?):**

We should detect as many regression and backward compatibility issues before merging a PR and to keep the master release-ready at any point in time.

**Approach/Hint to the implement solution (optional):**

**Comment by abdasgupta** [comment]
We already have such e2e tests in place. Currently, we are working on running those tests as part of PR
