### ISSUE TITLE
[Feature] Make it possible to have smaller auto-compaction-retention period for etcd

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#136]
**Feature (What you would like to be added):**

Make it possible to have smaller auto-compaction-retention period for etcd (both main etcd and the embedded ETCD during restoration).

**Motivation (Why is this needed?):**

High update rate can overflow memory and storage if `auto-compaction-retention` period is long. The current value is `24h`.
https://github.com/gardener/etcd-druid/blob/8307a62ad71ec0de3bf78de6d0e2bbc07700042c/charts/etcd/templates/etcd-bootstrap-configmap.yaml#L129-L130

**Approach/Hint to the implement solution (optional):**

We can either change the value to be smaller by default (`5m`?) and/or we can make it configurable via the `Etcd` resource spec.

**Comment by ishan16696** [comment]
should I also make `auto-compaction-mode`  configurable via `Etcd` resource spec?

**Comment by amshuman-kr** [comment]
> should I also make auto-compaction-mode configurable via Etcd resource spec?

Yes. Makes sense in terms of feature completeness.
