### ISSUE TITLE
[BUG] Fix failing test after 

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#160]
**Describe the bug:**
The following test case is failing after the commit https://github.com/gardener/etcd-druid/commit/72ec7a0d5d5b1a25dbacd0546897bf8239630755. 

**Expected behavior:**
No test cases should fail.

**How To Reproduce (as minimally and precisely as possible):**

Run `make test` on the commit https://github.com/gardener/etcd-druid/commit/72ec7a0d5d5b1a25dbacd0546897bf8239630755.

**Logs:**

```
• Failure [6.027 seconds]
Druid when etcd resource is created [It] if fields are set in etcd.Spec and TLS enabled, the resources should reflect the spec changes 
/tmp/build/a94a8fe5/pull-request-gardener.etcd-druid-pr.master/tmp/src/github.com/gardener/etcd-druid/controllers/etcd_controller_test.go:482

  Expected
      <string>: ConfigMap
  to match fields: {
  .Data."bootstrap.sh":
  	Expected
  	    <string>: "...tus = '143'..."
  	to equal               |
  	    <string>: "...tus == '143..."
  }
  

  /tmp/build/a94a8fe5/pull-request-gardener.etcd-druid-pr.master/tmp/src/github.com/gardener/etcd-druid/controllers/etcd_controller_test.go:882
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by amshuman-kr** [comment]
This is blocking PR merge for https://github.com/gardener/etcd-druid/pull/156 probably other PRs too.

**Comment by ishan16696** [comment]
Hi @amshuman-kr,
My PR [this](https://github.com/gardener/etcd-druid/pull/153)  had a fix for this test case but we don't want Abhishek to rebase again, so I removed this fix from my PR and Abhishek include this fix in his [PR](https://github.com/gardener/etcd-druid/pull/133)
