### ISSUE TITLE
[Feature] Avoid locks during reconciliation

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#171]
**Feature (What you would like to be added):**
 
#163 introduced locking the main and custodian controller for every update to the `Etcd` resource and its status.

This should be avoided and the race conditions in the tests should be solved in a different way.

**Motivation (Why is this needed?):**

Such synchronisation will lead to performance bottlenecks.

**Approach/Hint to the implement solution (optional):**

 Use `StatusWriter.Patch()`?
 
 Credit: @timuthy

**Comment by abdasgupta** [comment]
I tried with patch and removed locks. But the unit tests gave race condition error. Should I raise a PR with the changes for patch, just for your review?

**Comment by amshuman-kr** [comment]
Hmm. Yes, you can raise a draft PR.

**Comment by amshuman-kr** [comment]
I think I found the reason for the race-condition while using `Status().Patch()` or `Status.Update()` without synchronisation. The race condition seems to occur when the `client-go/rest` tries to decode the response back into the object (see the error trace below).

This in turn seems to relate to a bug in the `DeepCopy` implementation where some string pointers are not deeply copied. When I try passing a "freshly constructed" object (with only `TypeMeta` and `ObjectMeta` and without spec and status) to `Status().Patch()`, the race-conditions disappear.

I think, the real fix should be in `DeepCopy`, though.

**Comment by amshuman-kr** [comment]
> I think, the real fix should be in DeepCopy, though.

I tried to re-generenate the `DeepCopy` methods. But the race-conditions persist. So, for now, the only thing that mitigates the problem is to pass a "freshly constructed" object to `Status()/.Patch()`, as mentioned earlier.

**Comment by amshuman-kr** [comment]
> When I try passing a "freshly constructed" object (with only TypeMeta and ObjectMeta and without spec and status) to Status().Patch(), the race-conditions disappear.

To be clear, this is really a work-around and it certainly will only work with `client.RawPatch()` and not with `client.MergeFrom()` or anything else that depends on the spec/status content of the object passed to `Status().Patch()`.

**Comment by amshuman-kr** [comment]
I think I found the root cause. The auto-compaction config in common config seems to be not deeply copied.
```
# Before DeepCopy
Common:v1alpha1.SharedConfig{AutoCompactionMode:(*v1alpha1.CompactionMode)(0xc0007ee380), AutoCompactionRetention:(*string)(0xc0007ee390)}
# After DeepCopy
Common:v1alpha1.SharedConfig{AutoCompactionMode:(*v1alpha1.CompactionMode)(0xc0007ee380), AutoCompactionRetention:(*string)(0xc0007ee390)}
```

I can now see that https://github.com/gardener/etcd-druid/pull/157 forgot to generate `DeepCopy`. I tried generating it now. But for some reason, I still see the auto-compaction config not deeply copied.

Will dig some more.

**Comment by amshuman-kr** [comment]
> But for some reason, I still see the auto-compaction config not deeply copied.

Mystery solved. After separating `api` into its own go module in https://github.com/gardener/etcd-druid/pull/169, the rest of `etcd-druid` uses the [vendored api](https://github.com/gardener/etcd-druid/tree/master/vendor/github.com/gardener/etcd-druid/api/v1alpha1). So, re-generating the `DepCopy` functions followed by `make revendor` fixed the race-condition.

**Comment by amshuman-kr** [comment]
@abdasgupta Can you please change `Status().Patch()` to `Status().Update()` (that fixed all failing test cases after race-conditions were fixed)? Let's revisit using `Status.Patch()' as a separate issue.
