### ISSUE TITLE
[Feature] Simplify reconciliation by simplifying claim logic for StatefulSet, Service and ConfigMap based on Etcd resource name

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#186]
**Feature (What you would like to be added):**

The reconciliation flow of `etcd-druid` includes claiming from potentially multiple pre-existing `StatefulSet`, `Service` and `ConfigMap` objects if they exist. This is done by [selecting the objects based on `spec.selector` in the `Etcd` resource](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L192), [claiming one of the matching objects (if any)](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L82-L153) and [deleting the rest of the objects (if any)](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/etcd_controller.go#L600). If no matching objects are found then a [new object is created](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/etcd_controller.go#L646).

The logic of claiming from multiple pre-existing objects objects based on`spec.selector` was done because of the following reasons.
1. Migration from the time before `etcd-druid` was introduced. I.e. adopting objects created from the time before `etcd-druid` was introduced minimised and simplified clean up.
2. Keeping options open before multi-node ETCD design was finalised to use a [single `StatefulSet` for all the members of an ETCD cluster](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#kubernetes-context). Another alternative of using [one `StatefulSet` for each member of an ETCD cluster](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#alternative-1) was still open at that time.

Now that the migration scenario as well as the multi-node design don't need the functionality of claiming from multiple pre-existing objects, we can simplify the claim logic to just pick the object to be claimed by the same name as the `Etcd` resource . We will still need the [claim functionality](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L82-L153) to mark it as claimed, of course.

**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**

**Comment by abdasgupta** [comment]
Closing this issue as we no longer follow claim logic
