### ISSUE TITLE
[BUG] Fix reconciliation predicates to fully comply with gardener extension contract

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#196]
**Describe the bug:**
The main controller reconciles changes to `Etcd` resource `spec` even if `gardener.cloud/reconcile` annotation is not added. This is against the [gardener extension contract](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md).

**Expected behavior:**
The main controller should use the predicates in such a way that changes to the `Etcd` resource `spec` are reconciled only when the resource is also annotated appropriately. For example, see [here](https://github.com/gardener/gardener/blob/609107f2b19584315cc639b52668f73820dfc44a/extensions/pkg/controller/backupbucket/controller.go#L60-L72).

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID : v0.5.2
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by shreyas-s-rao** [comment]
@amshuman-kr from the [extension contract](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md), I see that `They have to remove this annotation as soon as they begin with their reconcile operation and maintain the status of the extension resource accordingly`. Whereas, in the druid controller, we actually remove the operation annotation *after* performing the reconciliation, while updating the etcd status ([refer](https://github.com/gardener/etcd-druid/blob/787692e268fcf2368113d34426ae9f1cc05bd29a/controllers/etcd_controller.go#L245-L261)). This behavior has to be changed as well right?

**Comment by amshuman-kr** [comment]
Thanks for the review @shreyas-s-rao! AFAIK, the important bit is to make sure the spec reconciliation happens only when the annotation exists. If we remove the annotation at the beginning or end of reconciliation doesn't much affect the contract.

We can still do the change to move the removal of the annotation earlier in the reconciliation, but I would suggests let's pick this after multi-node. WDYT?

**Comment by shreyas-s-rao** [comment]
Sounds good @amshuman-kr . Just saw the deviation from ideal behavior so raised it here.

**Comment by shreyas-s-rao** [comment]
I've raised an issue for it here -> https://github.com/gardener/etcd-druid/issues/204
