### ISSUE TITLE
[Feature] Enhance gardener grafana dashboards for multi-node

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#221]
**Feature (What you would like to be added):**
Enhance gardener grafana dashboards for the new changes introduced by the multi-node stories.

**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**
Members-overview section, individual graph lines per member on etcd dashboard.
Most etcdbr graphs remain same, but need to pick metrics from the leader sidecar.

**Comment by abdasgupta** [comment]
Depends on #340
