### ISSUE TITLE
Implement  "component" concept for all the K8s resources

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#278]
**Feature (What you would like to be added):**
Implement  "component" concept for all the K8s resources to replace the [chart](https://github.com/gardener/etcd-druid/tree/v0.7.3/charts/etcd/templates) that we use in Druid and instead build the K8s resources within the code

**Motivation (Why is this needed?):**
To achieve a better test-ability and more control how the client is used to reconcile the objects (e.g. used verb `UPDATE` vs `PATCH`) or how merging objects will be implemented. The same approach was taken in `gardener/gardener`.

Please see [this comment](https://github.com/gardener/gardener/issues/2754#issuecomment-678301676) for more information.

**Approach/Hint to the implement solution (optional):**
Please follow [this PR](https://github.com/gardener/etcd-druid/pull/262) for the idea to implement.

- [x] Lease: #262
- [x] Service: #273
- [x] ConfigMap: #193
- [x] PodDisruptionBudget #430 
- [x] StatefulSet #365
- [x] RBAC (Role + RoleBinding) #538 #539 
- [x] ServiceAccount #535 
- [x] https://github.com/gardener/etcd-druid/pull/559

**Comment by abdasgupta** [comment]
cc @ashwani2k @aaronfern @ishan16696 @timuthy

**Comment by abdasgupta** [comment]
We have two of the k8s resources to be left to be converted with golang code. We will pick them up when we are less overloaded.

**Comment by shreyas-s-rao** [comment]
Added another task to the original list in issue description: `Job (for EtcdCopyBackupsTask Controller)`

**Comment by seshachalam-yv** [comment]
Raised PRs for followings components,

- ServiceAccount - #535
- Role - #538
- RoleBinding - #539
