### ISSUE TITLE
[Feature] e2e tests for multi-node etcd

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-druid#286]
**Feature (What you would like to be added):**
We should add e2e tests for multi-node etcd scenarios. These tests should be executable by our CI pipeline as well as locally on dev machines.

**Motivation (Why is this needed?):**
To ensure quality and robustness of the feature as well as avoid regressions in the future. [Multi-node etcd](https://github.com/gardener/etcd-druid/tree/master/docs/proposals/multi-node) is a complex setup of many distributed and orchestrated steps with different use cases, e.g. bootstrap, scale-{up,down}, member recovery, cluster recovery, quorum loss.

**Approach/Hint to the implement solution (optional):**
- [x] #296
- [x] Enable e2e test execution in prow.
- [x] Implement multi-node specific e2e tests based on scenarios described [here](https://github.com/gardener/etcd-druid/tree/master/docs/proposals/multi-node#decision-table-for-etcd-backup-restore-during-initialization).

Further test cases can be collected in this issue.

**Comment by abdasgupta** [comment]
e2e tests to handle multi-node scenario are covered in:
https://github.com/gardener/etcd-druid/pull/418
https://github.com/gardener/etcd-druid/pull/451

**Comment by shreyas-s-rao** [comment]
Integration of e2e tests with pipeline tracked by https://github.com/gardener/etcd-druid/issues/465

**Comment by shreyas-s-rao** [comment]
Closing as https://github.com/gardener/ci-infra/pull/553 enables e2e tests via prow jobs.
/close
