### ISSUE TITLE
[Feature] Readiness Probe in multi-node etcd

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#288]
**Feature (What you would like to be added):**
Currently, [readinessProbe of etcd](https://github.com/gardener/etcd-druid/blob/master/charts/etcd/templates/etcd-statefulset.yaml#L55-L60) is set to an endpoint `/healthz` of [HTTP server](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/server/httpAPI.go#L168) running in backup sidecar.
This behaviour needed to be updated as readinessProbe of `clustered-etcd`  should depend on whether there is etcd-leader present or not then only it should serve the incoming write requests.

**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**
 Approaches :
1.  `ETCDCTL_API=3 etcdctl endpoint health --endpoints=${ENDPOINTS} --command-timeout=Xs` 
`etcdctl endpoint health` command performs a GET on the "health" key([source](https://github.com/etcd-io/etcd/blob/main/etcdctl/ctlv3/command/ep_command.go#L126-L133))
    - fails when there is no etcd leader or when Quorum is lost as I think GET request will fail if there is no etcd leader present.

 **Advantage** of this Method  (`etcdctl endpoint health`).
   -  We don't have to worry about [such scenarios](https://github.com/gardener/etcd-druid/issues/147) causing outage as now snapshotter fails won't fails the readinessProbe of etcd.
   
  **Disadvantage** of this Method  (`etcdctl endpoint health`).
  -  If there is no Quorum present, kubelet will also mark the `etcd-followers` as `NotReady`.
  - [Owner check feature](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/server/backuprestoreserver.go#L261-L267) depends on endpoint `/healthz` of [HTTP server](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/server/httpAPI.go#L168) because when Owner check fails it fails the readinessProbe of etcd by setting the [HTTP status to 503](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/server/backuprestoreserver.go#L267) but this Owner check in multi-node scenario is already being discussed [here](https://github.com/gardener/etcd-druid/issues/242).
  
  
2.  Use endpoint `/healthz` of HTTP server running in backup sidecar with modifications in such a way that whenever `backup-restore leader` is elected it should set `HTTP server status to 200` for itself as well for all  `backup-restore followers`.

**Comment by timuthy** [comment]
> fails when there is no etcd leader or when Quorum is lost as I think GET request will fail if there is no etcd leader present.

I can confirm that as long as the reads happen with linaerizable consistency (default - https://etcd.io/docs/v3.3/learning/api_guarantees/#linearizability)

> If there is no Quorum present, kubelet will also mark the etcd-followers as NotReady.

I'm not sure if this is really a problem because for when we need to recover from a quorum loss, we anyhow have to start again from scratch, i.e. create a new cluster from backup and scale out again (details tbd).

**Comment by timuthy** [comment]
@ishan16696 can we move this issue to https://github.com/gardener/etcd-backup-restore as the implementation is very specific to the etcd-br component?

**Comment by ishan16696** [comment]
Hi @timuthy ,

I have opened an issue there https://github.com/gardener/etcd-backup-restore there with updated points. 
PTAL !!!.
closing this as we have moved to https://github.com/gardener/etcd-backup-restore/issues/423.
/close
