### ISSUE TITLE
[Feature] Expose the metrics fro multinode ETCD

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#358]
**Feature (What you would like to be added):**
Expose the metrics that is listed in the [running doc](https://github.com/gardener/etcd-druid/blob/master/docs/multinode-metrics.md)
**Motivation (Why is this needed?):**
We need to expose the metrics in the codebase so that prometheus can collect the metrics and convert them into meaningful representation for the support.
**Approach/Hint to the implement solution (optional):**

**Comment by ishan16696** [comment]
Mentioning the metric which I found while doing [feature of single member restoration in multi-node etcd](https://github.com/gardener/etcd-backup-restore/pull/509):
 Add metrics: 
- Whether the single node restoration in multi-node etcd was successful or not.
-  How much time it took while restoration. 
like we did in single node restoration (refer [here](https://github.com/gardener/etcd-backup-restore/blob/6e4d52141063a193953ffd999207fe52d2c14796/pkg/initializer/initializer.go#L96-L100)).
