### ISSUE TITLE
[BUG] Statefulset updation fails as druid attempts to update forbidden fields

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#404]
**Describe the bug:**
With the new component model for statefulset, and the removal of claim/recreation logic for statefulsets, druid uses certain default values in the statefulset spec. This works well for newly created etcds, but older ones that were created with the old default values, fail to be updated by druid since updates to certain fields in the statefulset spec is forbidden, with the error message like
```
Error while waiting for Etcd xyz to become ready: StatefulSet.apps "etcd-main" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

Examples of such "forbidden" fields are `PodManagementPolicy` and `ServiceName`.

**Expected behavior:**
Druid should have respected the old values of the statefulset, or recreated the statefulset with the new values for these forbidden fields.

**How To Reproduce (as minimally and precisely as possible):**
Create an etcd resource using the [sample etcd resource](https://github.com/gardener/etcd-druid/blob/master/config/samples/druid_v1alpha1_etcd.yaml), using etcd-druid `v0.8.5` or below. Once the etcd becomes ready, stop running druid, checkout `v0.12.0` and re-run druid. Reconciliation of the etcd will fail.

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID : `v0.12.0`
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:
Temporarily fixed with https://github.com/gardener/etcd-druid/pull/401, https://github.com/gardener/etcd-druid/pull/402 and https://github.com/gardener/etcd-druid/pull/403.
The permanent solution is for druid to check if the statefulset patch includes changes to forbidden/immutable fields, and if required recreates the statefulset with the new values.

**Comment by timuthy** [comment]
FMPOV this issue has two sides:

1. The change is initiated by Etcd-Druid, e.g. `sts.spec.serviceName`. This means, that we require the resulting statefulset to change the field value when a certain feature is requested, e.g. the cluster is scaled-up. We can detect such a change and should recreate the statefulset as done [here](https://github.com/gardener/etcd-druid/blob/49c69009afb8c7c094f0daff7c641d6bc6c43a4b/pkg/component/etcd/statefulset/statefulset.go#L78).
2. The change is initiated by the consumer, e.g. changing `etcd.spec.storageClass`. Here, Kubernetes as well forbids updating the `sts.spec.volumeClaimTemplates[].Spec.StorageClassName` and instead forces the user to re-create the entire statefulset if they really want to change the field.
I think we should do the same in Etcd-Druid: Make those fields immutable and forbid updates via a validating webhook.

**Comment by timuthy** [comment]
I opened https://github.com/gardener/etcd-druid/issues/409 for the `2.` case.
