### ISSUE TITLE
[BUG] Validation that selector matches labels in etcd.Spec

### ISSUE THREAD

**Issue by georgekuruvillak** [gardener/etcd-druid#45]
**Describe the bug:**
The statefulset prevents creation of statefulsets where the labels in the template does not match the selector. Etcd however does not have a similar validation.
**Expected behavior:**
Etcd resource creation should through an error when the labels in the template does not match the selector.
**How To Reproduce (as minimally and precisely as possible):**
Have the selector field set so that it does not match the template in the statefulset.
**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by abdasgupta** [comment]
This issue doesn't apply anymore to the current design of Druid. Reopen if needed
