### ISSUE TITLE
[Feature] Improvement Proposal for `kubectl` Custom Columns of `etcd` Resources

### ISSUE THREAD

**Issue by vlerenc** [gardener/etcd-druid#453]
**Feature (What you would like to be added):**
I am not certain, what exactly the `etcd` resource `READY` column in the `kubectl` output depicts and find it confusing. At first, I was confused why all 3 pods must be ready for the `etcd` resource to become ready. What I care for as an operator is that the quorum is given and the `etcd` cluster is available/can serve requests. Only with second priority, I like to know what the state of the `pods` is, but for that I can also take a look at them directly or the `statefulset`. I saw that the `etcd` resource has a `Quorate` condition, which is probably what I am looking for. I would prefer to see that over the `AllMembersReady` condition. When I think about it, showing the `BackupSucceeded` condition would also make sense and not widen the `kubectl` output too much.

Then I noticed, that in some cases, it doesn't even mean what I thought it means, e.g. when I worked through the permanent quorum loss runbook, I noticed that my `etcd` resource is `READY=false` while it runs with 1 perfectly `ready` replica (before I need to scale it out to 3), even though `etcd` was up an serving requests just fine (I tested it with `etcdctl`).

<img width="1369" alt="Screenshot 2022-10-26 at 10 27 04" src="https://user-images.githubusercontent.com/4974203/198029570-48cd6b23-354f-44a5-a2ae-b98d5783e9b6.png">

I found that confusing and would welcome the following change:
- Show also the `Quorate` and `BackupSucceeded` conditions as columns in the `kubectl` output

**Motivation (Why is this needed?):**
As operator, I care more for those 2 conditions, then for the readiness condition, which I can look up also directly via `pods` or the `statefulset`.

**Comment by vlerenc** [comment]
P.S.: Personally, I use this command/alias now for `etcd` resources:
```
kubectl --namespace shoot get etcd -o=custom-columns='NAME:.metadata.name,DESIRED_REPLICAS:.status.clusterSize,ACTUAL_REPLICAS:.status.replicas,READY_REPLICAS:.status.readyReplicas,OVERALL_READY_STATUS:.status.ready,READY:.status.conditions[?(@.type=="AllMembersReady")].status,BACKUP:.status.conditions[?(@.type=="BackupReady")].status,QUOROM:.status.conditions[?(@.type=="Ready")].status'
```
...yielding:
```
NAME        DESIRED_REPLICAS   ACTUAL_REPLICAS   READY_REPLICAS   OVERALL_READY_STATUS   READY   BACKUP   QUOROM
etcd-main   3                  3                 3                true                   True    True     True
```

**Comment by ashwani2k** [comment]
Just a thought, so we can keep `Quorate` and `BackupSucceeded` as default output and may be we can implement a `-o wide` option like we recently did for [MCM](https://github.com/gardener/machine-controller-manager/pull/746) for the remaining columns.
