### ISSUE TITLE
[Feature] Remove the use of `Render` method of the `chartrenderer.Interface`

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/etcd-druid#454]
**Feature (What you would like to be added):**
I would like the use of `Render` method of the `chartrenderer.Interface` to be removed from this project (currently used in `./controllers/etcd_controller.go` and `./controllers/etcdcopybackupstack_controller.go`)

**Motivation (Why is this needed?):**
The `Render` method is deprecated in favour of `RenderEmbeddedFS` and will be removed in the future. For more info check [this PR](https://github.com/gardener/gardener/pull/6165).

**Approach/Hint to the implement solution (optional):**
The current `Render` method can be replaced by `RenderEmbeddedFS` with some changes to file structure or the code can be refactored without the use of these methods.

**Comment by shreyas-s-rao** [comment]
We have refactored most of etcd-druid codebase now, and the controllers no longer render helm charts. Instead, we use the `ResourceOperator` model (similar to the g/g component model) to reconcile k8s resources, so we have gotten rid of usage of `chartrenderer` package. This issue can now be closed.

/close
