### ISSUE TITLE
[Feature] Kind-based druid e2e tests and pipeline integration

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#465]
**Feature (What you would like to be added):**
As a developer, I would like be able to easily run the e2e tests for etcd-druid without the need for an external cluster. Ideally, I would like to use a local [kind cluster](https://kind.sigs.k8s.io/docs/user/quick-start/) to do this, similar to [how gardener/gardener does it](https://github.com/gardener/gardener/blob/master/docs/development/testing.md#end-to-end-e2e-tests-using-provider-local).

I would also like to run these e2e tests as part of the CICD pipeline before every PR is merged, to ensure that we aren't required to manually run the e2e tests before every PR/release.  

**Motivation (Why is this needed?):**
Kind-based testing is quite convenient, as already demonstrated by gardener. It allows developers to easily test locally, and also to integrate with the CICD pipeline, which can spin up a kind cluster and run tests against it, rather than trying to procure a k8s cluster from elsewhere.

**Approach/Hint to the implement solution (optional):**

/area quality
/area testing

**Comment by timebertt** [comment]
Relevant presubmit and periodic jobs for g/g's default e2e test are configured here:
https://github.com/gardener/ci-infra/blob/7a6196b887987748732e58511de9df1560d06d7f/config/jobs/gardener/gardener-e2e-kind.yaml
I think, it's best to use prow for these jobs as we already have the infrastructure and experience there and can simply copy a lot of configuration, code, etc.

cc @oliver-goetz

**Comment by abdasgupta** [comment]
So, I checked resorted to concourse to enable running druid e2e tests. I am facing a problem there as well. Currently concourse steps are not able to run KIND. I probably have to make a docker image that will run a KIND cluster and use that cluster to run `make e2e`.

**Comment by shreyas-s-rao** [comment]
If that's the case, can we stick to provider `Local` for e2e tests, which can be run on prow? For it to work for the tests, we will need to run `local-path-provisioner` to provision the host volumes on the kind node that's running the test etcd.

Either this, or we need to enhance the local provider logic in druid to be able to create a new PVC specifically for the backup store, and mount it onto the `backup-restore` container and specify the path to the volume correctly, so that `etcdbrctl` can take local backups to this volume itself. This avoids the need to run `local-path-provisioner` every time we want to test local provider on druid.

@timuthy @abdasgupta WDYT?

**Comment by abdasgupta** [comment]
Oliver gave us a way to conduct e2e tests with remote storages and mount secrets in Prow jobs. Currently, I am trying that

**Comment by abdasgupta** [comment]
I raised https://github.com/gardener/etcd-druid/pull/513 and https://github.com/gardener/ci-infra/pull/553 for this

**Comment by shreyas-s-rao** [comment]
/reopen

Let's keep this open until https://github.com/gardener/ci-infra/pull/553 is merged and the prow job is stable, for correctness of the issue tracking.

**Comment by shreyas-s-rao** [comment]
Closing since https://github.com/gardener/ci-infra/pull/553 is merged and test runs are stable.
/close
