### ISSUE TITLE
[BUG] HVPA not able to scale etcd.

### ISSUE THREAD

**Issue by KesavanKing** [gardener/etcd-druid#47]
**Describe the bug:**
VPA recommender misses the permission to get scale subresource because of which VPA on etcd is not happening  

**Expected behavior:**
As load increases based on VPA recommendations , etcd should be scaled.

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID : 
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: All

**Anything else we need to know?**:

**Comment by swapnilgm** [comment]
Fixed via #48
