### ISSUE TITLE
[Feature] Move control plane with a multinode ETCD cluster from one seed to another

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#479]
**Feature (What you would like to be added):**
To Migrate control plane with a multinode ETCD cluster from one seed to another seed.

**Motivation (Why is this needed?):**
Currently, control plane migration of a multinode cluster is not possible. PVs of old seed cluster are not guaranteed to be available to new ETCD pods in new seed cluster. Hence, ETCD multinode cluster has to restore from snapshots. This is same scenario like permanent quorum loss. We don't support recovery from permanent quorum loss as of now. So, we need some way to actually migrate control plane with multinode etcd cluster.

**Approach/Hint to the implement solution (optional):**
Needs to be discussed.

**Comment by ishan16696** [comment]
#### To achieve control plane migration with a multinode ETCD cluster:
**Requirement:**
1. Etcd resource should also get created in target control plane namespace.
2. Etcd-druid should pick the etcd resource and creates all etcd resources like etcd peer svc, etcd client svc, config map, leases object, PVs, PVCs etc.
3. Etcd cluster should be up with same no. of replica as it was in source control plane with same cluster state.  


**Hurdle:**
As we know creating a etcd cluster from 0->3 replicas with restoration from backup-bucket is equivalent of recovery from quorum loss scenario and currently we don't support the restoration/recovery from quorum loss scenario.

**Approach:**
To achieve the control plane migration with a multinode ETCD, we will be using the scale-up feature of multi-node etcd.
1. First, we will try to bring the etcd cluster of 1 replica, restored from the backup-bucket.
2. Then, we will scale-up the etcd cluster from 1 replica to 3 replicas.
<img width="962" alt="Screenshot 2022-12-27 at 11 45 03 AM" src="https://user-images.githubusercontent.com/42602577/209621319-02140eca-e88a-456d-8c67-f203756e8453.png">


**Methods to achieve this scale-up scenario:**
1. Trigger a full snapshot to reduce restoration time and copy the backups to target bucket from source bucket. 
2. CPM should recognise that this is the CPM with multi-node etcd case, then create the exact same Etcd custom resources in target control plane namespace with [.spec.replica](https://github.com/gardener/etcd-druid/blob/09e62b2de053e45fe2faddc352180b3defd6164a/api/v1alpha1/etcd_types.go#L269) as `1` not `3`.
3. Let the etcd-druid pick this etcd resource and creates all necessary resources like configmap, etcd svc, lease etc.
4. As we know restoration moving from `0` to `1` replica will succeed.
5. Once etcd pod will move to `Ready` state, CPM can change the `.spec.replicas` from `1` to `3` to trigger scale-up scenario.


Alternative method (if above method don't work):
1. Trigger a full snapshot to reduce restoration time and copy the backups to target bucket from source bucket. 
2. CPM should create the exact same Etcd custom resources in target control plane namespace as it was in source control plane namespace.
3. Let the etcd-druid pick this etcd resource and creates all necessary resources like configmap, etcd svc, leases etc.
4. As we know restoration moving from 0->3 replica will fail.
5. Then CPM will have to automate only relevant steps mentioned in [playbook](https://github.com/gardener/etcd-druid/blob/master/docs/operation/Recover_From_Etcd_Permanent_Quorum_Loss.md) to recover from quorum loss. 



/cc @plkokanov @abdasgupta @shreyas-s-rao
