### ISSUE TITLE
[Feature] Dashboard for ETCD Compaction job

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#504]
**Feature (What you would like to be added):**
We need some easily understandable info about compaction jobs for operators. Operators need to understand when the last compaction jobs ran successfully, how many events it compacted, how much resources the job consumed, did it failed or passed. One good way to publish this info is through a new grafana dashboard.

**Motivation (Why is this needed?):**
To easily understand details about last run compaction job.

**Approach/Hint to the implement solution (optional):**
Metrics, specific to compaction jobs, needs to be collected and published through grafana dashboard.

**Comment by abdasgupta** [comment]
cc @ashwani2k

**Comment by abdasgupta** [comment]
This issue is dependent on #515 .

**Comment by abdasgupta** [comment]
![Compaction Dashboard Layout](https://github.com/gardener/etcd-druid/assets/15626057/a566a128-1e2d-4f01-8470-a023c72ada15)

**Comment by shreyas-s-rao** [comment]
@abdasgupta thanks for coming up with the outline. I would prefer if the top-right panel showed the duration for successful as well as failed jobs, colour-coded appropriately, so that the dashboard also informs us about failed jobs and whether they succeeded later on or not.

**Comment by abdasgupta** [comment]
@shreyas-s-rao I updated the image as per your suggestion

**Comment by abdasgupta** [comment]
Check https://github.com/gardener/gardener/pull/8206
