### ISSUE TITLE
[Feature] Expose metrics regarding compaction job

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#515]
**Feature (What you would like to be added):**
Metrics to gauge compaction job will be exposed.

**Motivation (Why is this needed?):**
Currently, we are not exposing metrics regarding compaction job. If compaction jobs are enabled across landscapes, we don't have anything to get an idea about how many times the compaction jobs ran successfully, how many resources the compaction jobs are consuming etc. The metrics will help to keep track of those numbers.

**Approach/Hint to the implement solution (optional):**
We had couple of rounds of discussions for the approach to implement the solution. @unmarshall summarised that there are four approaches that we can take to implement this:

There were 4 options that viable and 1 option was ruled out.
Option ruled out:
Metric server cannot be used for pushing custom metrics. [README](https://github.com/kubernetes-sigs/metrics-server) mentions the following:
```
Metrics Server is not meant for non-autoscaling purposes.
```

# Viable Options & Considerations:
Option-1
---
Introduce a sleep in the compaction Job allowing prometheus to scrape all metrics out of the Job before completing the job.
This uses the pull approach and no push gateway is required.

Option-2
---
Leverage etcd-druid which is already a long-running pod and expose the metrics out of it which will then be scraped by prometheus.
Case in point: Cron jobs also create Job resources, the controller is then responsible for collecting making job metrics available for push/pull.

Option-3
---
Use push gateway from prometheus which is then provisioned per shoot control namespace. A compaction job which is provisioned within the same namespace can then use the direct service endpoint to push to it.
Istvan has to do some research on what is the best way to setup a push gateway (with(out) disk, thereby making it a sts or a regular deployment).
Other drawback: In a HA setup of the control plane, entire monitoring stack is not HA. This means that in case of a zone outage if the prometheus and push gateway are in the failed zone and push gateway is also setup as a STS then they will not be available.
NOTE: Today access to prometheus is not TLS enabled. However, monitoring team has a mandate to enable TLS to meet the product security requirements. Push gateway will be one more component for which key management (including rotation) will need to be done.

Option 4
---
Use prometheus remote API to directly write to it. Monitoring team is evaluating this for federation to circumvent the firewall restrictions. However, this is not idiomatic way of pushing metrics from a metrics producer.

# Final Approach Selection and Rationale
We had another round of discussion to figure out the best option. 
- **We ruled out option 1** because having a `sleep` command inside a job seemed hack approach as - 
    -  Firstly, it wastes unnecessary CPU cycles.
    -  Secondly, we always have to find a magic number for `sleep` to run, so that Prometheus can scrape it timely.
    - Third, Currently, etcd-backup-restore starts a HTTP server (which also hosts the /metrics endpoint) only under the "server" subcommand, so starting this HTTP server for other subcommands such as compact requires a re-design of the component, as mentioned in https://github.com/gardener/etcd-backup-restore/issues/544#issuecomment-1270339794

- **We ruled out option 3** for now because
  -  If implemented, we have to maintain life-cycle of another new server named pushgateway server. 
  -  We may have to make it HA compatible as well.

- **Option 4 is ruled out** because it's not meant for end consumers to use.

- **Option 2 is looking promising as of now**. Druid needs to open metrics endpoint. Then we need to collect metrics related to the job by druid. 

Next Steps:
---
- [ ] ETCD Druid enables metrics endpoint either by starting up a server or by leveraging metrics endpoint of controller manager.
- [ ] prometheus server in each shoot namespace should collect metrics from respective druid metrics endpoint.
- [ ] Expose the compaction metrics as decided by ETCD Druid team.

So far, following metrics regarding jobs are decided to be exposed by Druid:

1. Increase a metrics counter if the current job is successful.
2. Increase a metrics counter if the current job failed.
3. Gauge CPU consumed by last running job.
4. Gauge Memory consumed by last running job.
5. Time taken by currently running job to complete.
6. Gauge for number of events to be compacted

**Comment by abdasgupta** [comment]
Metrics that I thought about:
1. Number of jobs those are successfully completed.
2. Number of jobs those went into error.
3. CPU consumed by currently running job.
4. Memory consumed by currently running job.
5. Time taken by currently running job to complete.

@ishan16696 @ashwani2k @aaronfern @shreyas-s-rao do you have idea about any other metrics that can be collected regarding compaction job?

**Comment by shreyas-s-rao** [comment]
Thanks @abdasgupta. Can you also add the following snapshot-related metrics:
1. Compacted snapshot revisions (`start` and `end`) - tells us how many revisions were compacted. At the moment, default value for events-threshold is 1 million, but this can change anytime, or we might introduce a way to manually run a compaction job. Hence we will need the compaction job to emit metrics about how many revisions were compacted. 
2. Number of delta snapshots compacted
3. Total size of the compacted events - helps get a good idea of the impact of the compaction job in terms of size - gives an idea of the increase in bucket usage, required for measuring additional costs incurred from snapshot compactions

**Comment by ashwani2k** [comment]
How about following - 
1. Time since last successful compaction. (This should help to fine tune the configs or understand if for some shoots this is nearing the full snapshot time ) 

How about aggregated metrics across shoots at a seed level. (This can also provide us input w.r.t how different seeds/Infra's are behaving)
1. Avg time taken for compaction 
2. Max time taken for compaction 
3. Min time taken for compaction 
4. Failure %age  for compaction 

What about alerts -- Do we have all the possible alerts captured via the exposed metrics. 

Also have you considered https://github.com/gardener/etcd-druid/issues/502  while defining the overall scope of metrics - https://github.com/gardener/etcd-druid/issues/502

**Comment by abdasgupta** [comment]
Yes, we can include Snapshot revision numbers.. Also, we may include Time since last successful compaction. For each shoot, I decided to collect time taken by currently running compaction job. I think, that can give a very good idea about Avg time, Max Time, Min Time for compaction in a shoot. But if we need to calculate this metrics from seed level, I have to see whether I can implement it. I will keep that in mind

**Comment by abdasgupta** [comment]
Please check the following link for an overview of design on how we enable compaction job to push prometheus metrics:
https://gist.github.com/abdasgupta/7d41fd4b8bfda0ba62bb8773418c8aa0
