### ISSUE TITLE
Need to revisit some of the druid e2e tests which are using shell to execute some commands

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#554]
/kind enhancement

### What would you like to be added.
We have to revisit all druid end-to-end tests which requires to [exec into the container to execute some operations](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/utils.go#L558) on etcd or backup-restore and we have to perform those operations which are necessary for those tests via some different methods so we can avoid exec into containers of any pod.

### Motivation (Why is this needed?)
As going forward we have a plan to move to [Distroless container base image](https://github.com/gardener/etcd-custom-image/issues/16) in the future for etcd as well as backup-restore which will not contain `bash`,`curl` etc. and we won't be able to exec to into any containers to execute some operations on etcd or on backup-restore as there will be no shell present.

### Tests
- [x] TestName ["should create, test backup and delete etcd with backup"](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L78)  
     - [x] To populate the etcd with dummy data: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L102) and [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L128) 
     - [x] To get latest snapshot: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L91) and [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L109)
     - [x] To trigger on demand snapshot: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L121) and [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L132)
     - [x] To fetch etcd key-value: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L172)
     - [x] To trigger restoration by deleting data-dir: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_backup_test.go#L136)
 - [x] TestName ["Single member restoration"]()
      - [x] To trigger single member restoration by member dir: [here](https://github.com/gardener/etcd-druid/blob/080f0c75db2f6d3b588ded4a27087d9be98a5bd0/test/e2e/etcd_multi_node_test.go#L130)

 

### Acceptance Criteria
- Druid e2e tests shouldn’t be affected w.r.t functionality because of alternative method we will choose.

**Comment by aaronfern** [comment]
All e2e tests have been adapted to support the use of distroless images for `etcd-backup-restore` and `etcd-wrapper`
The tests now create a specialised debug pod into which the tests can exec into and perform `etcdctl` and other operations that are required for the tests 

Closing as tests have been adapted and the PR has been merged 
/close
