### ISSUE TITLE
[Feature] Introduce `Task`/`Operation` concept for out-of-band operations

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#590]
**Feature (What you would like to be added):**
Introduce a concept of `Out-of-band Operations` for etcd-druid.

**Definition of "out-of-band" operations:** 
Any on-demand operations which can be performed on `etcd cluster` and which do not alter the `Etcd` custom resource `spec`(desired state) can be called as "out-of-band" operations given that etcd cluster is running fine and healthy.

**Motivation (Why is this needed?):**
Etcd-druid is responsible for the reconciliation (creation, maintenance and deletion) of an etcd cluster. A user can specify an etcd cluster using the `Etcd` custom resource which druid sees and reacts upon by creating the required underlying Kubernetes resources such as statefulset, services, RBACs, etc. If the user wishes to make changes to this etcd cluster, they can do so by modifying the `Etcd` custom resource `spec` to the state they desire, and druid will reconciles the state of the etcd cluster to match the desired state.

But the etcd cluster also supports certain "out-of-band" operations. Operations that have nothing to do with the desired state of the etcd cluster. 

Examples of these are:
- To trigger on-demand full/delta snapshots via the backup-restore leader.
- To trigger on-demand snapshot compaction to get compacted full snapshot.
- Recovering from permanent quorum loss.
- Analyse and diagnose any etcd cluster health related issues.
- copying backups from one object store to another, which is already achieved by `EtcdCopyBackupsTask` controller and its dedicated CRD. Reasons for introducing this can be found in https://github.com/gardener/etcd-backup-restore/issues/356

Many of these functionalities can be achieved by baking in the logic into the existing etcd controller - any special operation on the etcd cluster can be triggered by adding an annotation on the `Etcd` object, which the etcd controller picks up upon reconciliation, and moves to a different code flow to perform the requested operation. While this is technically possible, it is not a desirable solution due to the following reasons:
- etcd controller is meant to reconcile the etcd cluster's state. Since the operation has no relation with the desired state of the cluster, it does not make much sense to trigger it via the `Etcd` object.
- many of the above mentioned operations have their own set of specifications or configuration items, and require to maintain a state, especially if they are long-running operations like recovering from quorum loss which typically need to be carefully orchestrated by druid and intermediate states need to be captured.

**Approach/Hint to the implement solution (optional):**

Create a framework for adding new `out-of-band operations` to etcd-druid, using which anybody can easily add new out-of-band functionality to druid operator.

**Comment by ishan16696** [comment]
I have updated the issue with definition of "out-of-band" ops and its scope.
 
Other tasks were also discussed but discarded due to following reasons:
- https://github.com/gardener/etcd-druid/issues/481
As volume deletion involves the deletion of volume which bring down the `1 etcd cluster member` in case of multi-node (entire etcd cluster in case of single node cluster), hence this leads to change in etcd's current state hence etcd-druid controller will try to bring it back to desired state, hence it is not an "out-of-band operation" by definition as it is interrupting with spec and status of etcd custom resource.

- Orchestrating the defragmentation on etcd cluster.
With [etcd-steward](https://github.com/gardener/etcd-steward), defragmentation on etcd cluster will be implemented with different approach by using the etcd leases: https://etcd.io/docs/v3.3/dev-guide/interacting_v3/#grant-leases

**Comment by shreyas-s-rao** [comment]
Thanks for updating the issue @ishan16696 .

The reason for removing `rolling of PVCs` from this scope is rather since volume spec (size, storage class) is defined in the `Etcd` spec, and is reconciled by druid, via the statefulset resource. Hence, any changes to the volume spec should be handled as part of regular reconciliation of the `Etcd` resource. That's why it cannot be an out-of-band operation, but rather a core operation as part of etcd reconciliation.

Coming to the second point, steward will handle this using etcd locks, as specified in https://github.com/gardener/etcd-steward/issues/4.

**Comment by ishan16696** [comment]
Thanks @shreyas-s-rao for adding more information and correcting me about etcd locks rather then etcd leases.
I have now updated my comments accordingly.

**Comment by renormalize** [comment]
For the sake of precision:

In @ishan16696's [comment](https://github.com/gardener/etcd-druid/issues/590#issuecomment-1842549397):

> As volume deletion involves the deletion of volume which bring down the 1 etcd cluster member in case of multi-node (entire etcd cluster in case of single node cluster), hence this leads to change in **etcd's current state** hence etcd-druid controller will try to bring it back to desired state, hence it is not an "out-of-band operation" by definition as it is interrupting with status of etcd custom resource of healthy etcd cluster.

Shouldn't the definition of what an "out-of-band" operation is also include that no change in the *status* of an `Etcd` resource is allowed by any operation that could be considered an "out-of-band" operation, as it currently only talks about the *spec* of an `Etcd` resource?

Any action which could change the *status* of the `Etcd` resource without changing the *spec* currently qualifies as an "out-of-band" operation.

If my understanding is wrong, please let me know! TIA.

**Comment by ishan16696** [comment]
> Shouldn't the definition of what an "out-of-band" operation is also include that no change in the status of an Etcd resource is allowed by any operation that could be considered an "out-of-band" operation, as it currently only talks about the spec of an Etcd resource?

Good point. As we know status is not owned by user but `status` is owned by resource there we don't have control, so "out-of-band" ops may or may not affect the `status` etcd resource.  For instance, understand this:
1. Operator has triggered a `out-of-schedule full snapshot` (no change in spec etcd resource).
2. But assume etcd resource status has field: `.status.lastFullSnapshotTime` then it will change as a full snapshot just has been taken.
Hence, I thought "out-of-band" ops may or may not affect the `status` etcd resourc as we don't have control over that. Even if today including `status` into definition fits, it may become ambiguous in future if new field is added in `etcd.Status`.

Now regarding this comment: https://github.com/gardener/etcd-druid/issues/590#issuecomment-1842549397 this is not relevant as of now, this is correct reason: https://github.com/gardener/etcd-druid/issues/590#issuecomment-1842721591
