### ISSUE TITLE
[Feature] Scrape compaction metrics available from druid controller by Cache Prometheus

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#622]
**Feature (What you would like to be added):**
Compaction metrics are available on metrics endpoints of Druid controller. Cache prometheus, running in the Garden namespace, should scrape the metrics endpoint for compaction metrics.
**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**
Add the metrics to whitelist if necessary

**Comment by shreyas-s-rao** [comment]
Closing now since https://github.com/gardener/gardener/pull/8206 is merged.
/close
