### ISSUE TITLE
[Feature] Federate compaction metrics to Control Plane prometheus from Cache Prometheus

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#626]
**Feature (What you would like to be added):**
#622 will bring compaction metrics from druid controller to Cache Prometheus. After that, the compaction metrics are needed to be federated to Control plan prometheus so that each shoot dashboard can show respective compaction job graphs. Control plane prometheus needs to federate cadvisor metrics of the job from cache prometheus as well.
**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**

**Comment by abdasgupta** [comment]
PR related to this issue : https://github.com/gardener/gardener/pull/8206

**Comment by shreyas-s-rao** [comment]
Closing since https://github.com/gardener/gardener/pull/8206 is merged.
/close
