### ISSUE TITLE
[Feature] Clearly segregate responsibilities between etcd and custodian controllers

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#644]
**Feature (What you would like to be added):**
Clearly segregate responsibilities between etcd and custodian controllers.

**Motivation (Why is this needed?):**
As already explained by @unmarshall in https://github.com/gardener/etcd-druid/issues/527#issuecomment-1635668002, etcd controller updates multiple `etcd.status` fields with the result of the reconciliation, while many of the same fields are regularly updated by custodian controller as part of its regular reconciliations. Etcd controller does not need to update these fields since it makes no sense to overstep on custodian controller's updates to the same fields, such as `etcd.Status.Ready` and `etcd.Status.Replicas`.

/assign
/milestone v0.20.0
/kind task
/area quality

**Comment by unmarshall** [comment]
Could be potentially linked to Live#3326. There was one such occurrence that recently happened in canary as well. There was no issue raised for the Canary occurrence. Symptoms for both these occurrences were similar - failed to update `ObservedGeneration`. One would think that it would get resolved upon restart of etcd-druid but even after restart the issue persisted.  It could improve once we segregated the responsibilities. So i am leaving a comment for a deeper investigation.

**Comment by shreyas-s-rao** [comment]
Superseded by #728 
/close
