### ISSUE TITLE
[Feature] Propagate `DeltaSnapshotRetentionPeriod` Flag to `etcd-backup-restore`

### ISSUE THREAD

**Issue by seshachalam-yv** [gardener/etcd-druid#650]
**Feature (What you would like to be added):**
Modify `etcd-druid` to propagate the `--delta-snapshot-retention-period` flag from the `Etcd` CRD to the `etcd-backup-restore` component.

**Motivation (Why is this needed?):**
The `etcd-backup-restore` component has recently introduced a `--delta-snapshot-retention-period` flag ([PR #640](https://github.com/gardener/etcd-backup-restore/pull/640)). This flag allows users to customize the retention period for delta snapshots, providing more flexibility for both Exponential and Limit-Based GC policies. To leverage this feature in `etcd-druid`, we need to modify `etcd-druid` to propagate this flag to the `etcd-backup-restore` component.

**Approach/Hint to the implement solution (optional):**

**Comment by shreyas-s-rao** [comment]
This has been completed as part of #651 
/close
