### ISSUE TITLE
[Feature] Set Request and Limit for CPU and Memory resources for compaction job

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#652]
**Feature (What you would like to be added):**
Compaction job needs to start with request and limit resources set.

**Motivation (Why is this needed?):**
Currently, compaction jobs have no request and limit set for CPU and Memory resources. A needy compaction job may use up all the resources and can cause starvation for other pods running in the same machine/node. If we consider the scenario of OOM kill, because of a compaction job system memory might be exhausted and OS may trigger OOM kill for any random pod. If we set request and limit resource for a compaction job, kubernetes scheduler might be aware of the needy compaction job and can issue a OOM kill only for the compaction job.

**Approach/Hint to the implement solution (optional):**
It's not much of a change to just set the request and limit for compaction job. But what can take longer is to find out what is the good value for request and limit so that, most of the compaction jobs can be accommodated and least number of pod kill happens by the Kubernetes scheduler 

Tasks: 
- [x] Requests
- [ ] Limits

**Comment by anveshreddy18** [comment]
Closing this in favour of #707 which will track requests & limits going forward.
