### ISSUE TITLE
[BUG] Make the metric metricsjobcurrent capture accurate job end time

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#685]
**Describe the bug:**
Currently the metric `metricsjobcurrent` is updated only when the delta event threshold crosses the limit and the compaction-controller in druid tries to create a new job or follow up the old job. But ideally, the metric should be updated even when the delta events are successfully compacted and the job is successful.

**Expected behavior:**
After a compaction job is run successfully and the delta events are compacted in backup, metric `metricsjobcurrent` should be updated to mark the end of the currently running job correctly in the dashboard. We can watch on the running compaction job status and as soon as the job is successful, we can update the `metricsjobcurrent` in the reconciler.

**How To Reproduce (as minimally and precisely as possible):**
Compaction job dashboard does not show the graph for `metricsjobcurrent` with correct end time of any successfully run compaction job.

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by shreyas-s-rao** [comment]
Looks like this will be solved by #698 as a beneficial side-effect.
