### ISSUE TITLE
[BUG] Improve error handling and reconciliation logic for compaction controller

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#698]
**Describe the bug:**
Compaction controller's purpose is to deploy a compaction job if it detects that a compaction job is necessary, due to possible triggers such as delta snapshot revision exceeding full snapshot revision by a given threshold (`etcd-events-threshold`), and in the future even upon the total delta snapshots' size crossing a certain threshold. Information about snapshot revisions is available today from snapshot leases maintained by the leading backup sidecar, and in the future will be published via [EtcdMember resource status](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/04-etcd-member-custom-resource.md#etcdmember).

Once the compaction job has been deployed, the controller requeues reconciliation. Until the compaction job succeeds or fails, the reconciliation must keep requeueing and checking compaction job status. Once compaction job succeeds/fails, the snapshot revision information will be updated by the compaction job itself, and compaction controller will know not to deploy a new compaction job until the next time a snapshot compaction trigger is received.

All the logic for reconciling the compaction job lies within [reconcileJob()](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L165). The issue with the current logic in compaction controller is that this method is called only [when the compaction threshold is reached](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L158-L160). But if a new full (regular scheduled) snapshot is uploaded by the leading backup sidecar while a compaction job is still running, then compaction controller never runs `reconcileJob()` because the snapshot revision threshold is no longer reached. This prevents the controller from reconciling the currently running compaction job to either cut it short, or atleast wait for completion and export the correct metrics for it.

Additionally, there are certain helper functions such as [getCompactionJobVolumeMounts()](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L334C6-L334C34), [getCompactionJobVolumes()](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L367C6-L367C29), [getCompactionJobEnvVar()](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L408C6-L408C28), which are used to generate the compaction job spec. All these functions make a call `utils.StorageProviderFromInfraProvider(etcd.Spec.Backup.Store.Provider)`, which returns the storage provider for the compaction job, and returns an error if the provider is unrecognised. But these functions do not correctly handle the error, and simply log the error and return an incomplete result which will cause the compaction job pod to fail to start due to a misconfigured job spec. Ideally, the call to `utils.StorageProviderFromInfraProvider()` must be made and error should be correctly handled within Reconcile() method itself, even before trying to generate the job spec. Additionally, the [store nil check](https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L104) being made initially in Reconcile() is also being made redundantly in all the helper functions, and must be removed.

There are other instances in the compaction controller where errors are not handled correctly, and simply logged, rather than blocking the deployment of the compaction job, for instance https://github.com/gardener/etcd-druid/blob/00274d0929b34e41486236946ec1488344212495/controllers/compaction/reconciler.go#L389-L392. These too need to be correctly handled.

**Expected behavior:**
Reconciliation should be precise, and must handle all cases of snapshots being taken by leading backup sidecar and compaction job. Errors must be correctly handled.

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by abdasgupta** [comment]
Already working on this

**Comment by shreyas-s-rao** [comment]
Resolved by #711 
/close
