### ISSUE TITLE
☂️  Etcd ConfigMap changes

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-druid#717]
One `ConfigMap` is created per etcd (etcd-main and etcd-events) today. We propose to do/relook at the following:

- [ ] Revive https://github.com/gardener/etcd-druid/pull/467 and ensure that the name of the ConfigMap's are consistent with all other resources that are created for an etcd resource. While doing this ensure that the new version of `druid` which now uses the new name properly reconciles the older configmap's having the older name.
- [ ] Make `snapshot-count` configurable See impact [here](https://etcd.io/docs/v3.4/op-guide/maintenance/#raft-log-retention). We can retain the default of 75000. Upstream default changes from 10000 to 100,000. We can revisit the current default if need be.
- [ ] #476

**Comment by ishan16696** [comment]
> initial-advertise-peer-urls and advertise-client-urls uses @ as delimiter. This is not really required. Have proper URLs.

open issue for this point: https://github.com/gardener/etcd-druid/issues/476

**Comment by ishan16696** [comment]
> Make snapshot-count configurable See impact [here](https://etcd.io/docs/v3.4/op-guide/maintenance/#raft-log-retention). We can retain the default of 75000. Upstream default changes from 10000 to 100,000. We can revisit the current default if need be.

Increasing the default `snapshot-count` to `100K` is not good as it will leads to more usage of memory.
kubeadm uses `snapshot-count` set to `10k`. https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/phases/etcd/local.go#L270C37-L270C40
Upstream etcd have also changed the default value of `snapshot-count` to `10k` https://github.com/etcd-io/etcd/pull/15408. They will bring this change in etcd `v3.6`.
