### ISSUE TITLE
[Feature] Move UseEtcdWrapper beta feature to GA feature

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#776]
**Feature (What you would like to be added):**

- [x] Move [UseEtcdWrapper feature](https://github.com/gardener/etcd-druid/blob/master/docs/deployment/feature-gates.md#feature-gates-for-alpha-or-beta-features) from beta stage to GA stage. #936 
- [x] Remove the prow job which runs [etcd-druid e2e tests with etcd-custom-image for master branch](https://github.com/gardener/ci-infra/pull/1080) as we will stop supporting the `etcd-custom-image` for druid versions > `v0.25`. https://github.com/gardener/ci-infra/pull/2757

**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**

**Comment by shreyas-s-rao** [comment]
@ishan16696 I feel we can remove point 3 in the issue, since we don't need to support etcd-custom-image anymore, because the feature gate will be moved to GA.

**Comment by ishan16696** [comment]
As far I remember, we discussed this and concluded that community might still be using `etcd-custom-image` (community user can still set `-use-etcd-wrapper=false` and consume druid) and we don't want to break the changes for them, so that's why it's required to have a prow job to run druid e2e tests with `etcd-custom-image`.

**Comment by shreyas-s-rao** [comment]
@ishan16696 I think that is already taken care of by the release-specific proe job manifests at https://github.com/gardener/ci-infra/tree/master/config/jobs/etcd-druid/releases. So any PRs on older release branches will run both the prow jobs. 

The latest prow jobs that we maintain will run against master branch PRs. For this, only one prow job is now sufficient, once the feature gate becomes GA.

**Comment by ishan16696** [comment]
> I think that is already taken care of by the release-specific proe job manifests at https://github.com/gardener/ci-infra/tree/master/config/jobs/etcd-druid/releases. So any PRs on older release branches will run both the prow jobs.

ok, then that is only true for older releases but for new releases.
As I mentioned above "community users can still set flag `--use-etcd-wrapper` to `false` and consume druid", if we are dropping the support for etcd-custom-image from druid then there is no point of having flag `--use-etcd-wrapper` which might let user to give a illusion of it can avoid using wrapper, druid should directly deploys etcd-wrapper without any flag indication. I hope it make sense.

**Comment by shreyas-s-rao** [comment]
> community users can still set flag --use-etcd-wrapper to false and consume druid

@ishan16696 no, that will not be possible. With druid:v0.25.0, the feature gate becomes GA and is locked to true, so users can never disable it once they move to v0.25.0. 

`use-etcd-wrapper` is a config flag used by etcd-backup-restore to determine whether to call the `/stop` endpoint on etcd-wrapper or not. Because etcd-backup-restore can still be run against vanilla etcd or even etcd-custom-image, and not necessarily against just etcd-wrapper.
