### ISSUE TITLE
☂️ Improve documentation

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#813]
**How to categorize this issue?**

/area documentation
/kind enhancement

**What would you like to be added**:

Improve documentation of etcd-druid repo, to make it easy for anybody to use druid and contribute to it.

- [x] Revamp `README.md` https://github.com/gardener/etcd-druid/pull/851
- [ ] Changes to `docs/development`
   - [x] Add `testing.md` to describe how testing should be done. Depends on https://github.com/gardener/etcd-druid/issues/852
   - [ ] Add `etcd-cluster-components.md` describing all components that are provisioned for an etcd cluster.
   - [ ] Combine all `getting-started-locally-*` into a single markdown file.
- [ ] Changes to `docs/deployment`
   - [ ] Revamp `cli-flags.md`
   - [ ] Minor changes required to `feature-gates.md` - re-arrangement of sections and making it more concise.
   - [ ] Add `getting-started.md` which describes on how to setup druid in productive environment.
- [ ] Add new section for monitoring: `docs/monitoring`
   - [ ] Move existing metrics.md here and refactor it by only giving details of metrics specific to druid and only providing links to markdowns in etcd-backup-restore and etcd-wrapper repos where metrics exposed out of those repos are detailed out.
   - [ ] Add `profiling.md` which details out on how to profile etcd-druid deployment.
- [ ] Add new section for operations: `docs/operations`
   - [ ] Add one markdown (recovery.md) detailing recovery from transient and permanent quorum loss in single and multi-node etcd clusters
- [ ] Add a new section `docs/usage`
   - [ ] create new markdown `copy-backups.md` and describe the functionality and its usage.
   - [ ] create new markdown `deploying-etcd-clusters.md` which describes how to configure and deploy/reconcile etcd clusters.
- [ ] Add a new section `docs/benchmark` where existing markdown on benchmarking is moved.
- [ ] At the root of the project change `CONTRIBUTIONS.md` - currently it points to gardener webpage.
- [ ] Use [mkdocs](https://squidfunk.github.io/mkdocs-material/) to generate site for markdown documentation and host them as github pages.

**Comment by anveshreddy18** [comment]
@unmarshall I think there is a need to create a new issue to track the uncompleted subtasks in this, such as hosting on Github pages, and `copy-backups.md` file under `docs/usage` as this one got closed.
