### ISSUE TITLE
Wrong annotations in Quorum loss doc

### ISSUE THREAD

**Issue by StenlyTU** [gardener/etcd-druid#858]
**How to categorize this issue?**

/area quality
/kind question

**What happened**:

I've recently had to restore ETCD from Quorum loss following the guide under [.docs/operations/recovery-from-permanent-quorum-loss-in-etcd-cluster.md](https://github.com/gardener/etcd-druid/blob/master/docs/operations/recovery-from-permanent-quorum-loss-in-etcd-cluster.md#quorum-loss-in-etcd-cluster) and the annotations under point 1 didn't prevent reconciliation.
```
kubectl annotate etcd etcd-main druid.gardener.cloud/suspend-etcd-spec-reconcile=

kubectl annotate etcd etcd-main druid.gardener.cloud/disable-resource-protection=
```

In [previous](https://github.com/gardener/etcd-druid/blob/ff01993c8891bde8e6904b416607ce6307521b9f/docs/operations/recovery-from-permanent-quorum-loss-in-etcd-cluster.md) revision of the file the annotation `etcd-main druid.gardener.cloud/ignore-reconciliation="true"` worked as expected.

@unmarshall Can you check?
cc @adenitiu

**What you expected to happen**:

The annotations to prevent reconciliation

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- etcd-druid version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by renormalize** [comment]
@StenlyTU 
Quite a bit of refactoring has happened in etcd-druid, and the current doc on master refers to the newer annotation which hasn't yet been released. 

I guess checking out the release tag 0.22.x which is running and following the doc present in that commit would currently fix your issue.

**Comment by ishan16696** [comment]
Hi @StenlyTU ,
As I mentioned in the issue, for our landscapes we have to use this doc: https://github.com/gardener/etcd-druid/blob/hotfix-v0.22/docs/operations/recovery-from-permanent-quorum-loss-in-etcd-cluster.md as in our landscapes we are using druid `v0.22.4`. Things have changed for master branch as mentioned in this comment: https://github.com/gardener/etcd-druid/issues/858#issuecomment-2290899703
Closing this issue.
/close
