### ISSUE TITLE
v0.23.2 druid fails to reconcile an older versioned cluster when at least one etcd-member goes down prior to update of STS

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-druid#908]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

v0.23.x version of etcd-druid changes the mount paths for TLS artifacts. This change is reflected in 2 places:
- ConfigMap
- StatefulSet - CLI args and Volume mount paths for TLS artifacts

Following are the changes to TLS volume paths:
| Container | Version < v0.23.x  | Version >= v0.23.x |
| ------------- | ------------- | ------------- |
|etcdbr | Name: `client-url-ca-etcd`<br/>MountPath: `/var/etcd/ssl/client/ca`  |  Name: `etcd-ca`<br/>MountPath:`/var/etcd/ssl/ca` | 
| etcdbr| Name:`client-url-etcd-server-tls`<br/>MountPath:`/var/etcd/ssl/client/server` | Name:`backup-restore-sever-tls`<br/>MountPath:`/var/etcdbr/ssl/server`  |
| etcdbr| Name:`client-url-etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client` |
| etcd-wrapper| Name:`client-url-ca-etcd`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-ca`<br/>MountPath:`/var/etcd/ssl/ca` |
| etcd-wrapper| Name:`client-url-etcd-server-tls`<br/>`/var/etcd/ssl/client/client` | Name:`etcd-server-tls`<br/>MountPath:`/var/etcdbr/ssl/server` |
| etcd-wrapper| Name:`client-url-etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-client-tls`<br/>MountPath:`/var/etcdbr/ssl/client` |

Consider the following situation:
You have an etcd cluster which was setup using druid version v0.22.x this means that it will have the older volume mounts and also the same paths will also be reflected in the etcd ConfigMap.
Now when you upgrade druid to v0.23.y and annotate the `Etcd` resource with `gardener.cloud/operation=reconcile` then etcd-druid will first change the ConfigMap and update it with the new paths for TLS artifacts. Then it goes and attempts to update StatefulSet. Now imagine that just before the STS is updated one or more pods in the etcd-cluster go down. When they come up again, then it will now pick up the new ConfigMap and will attempt to start the etcd with the new TLS artifact paths. Since the volume mounts have not been changed yet (as this is only going to happen when STS is updated) the pod will never come up.
It will throw up the following error:
```
{"level":"fatal","ts":"2024-11-07T17:28:15.570Z","caller":"etcd-wrapper/main.go:58","msg":"error during start or run of etcd","error":"open /var/etcd/ssl/ca/bundle.crt: no such file or directory","stacktrace":"main.main\n\t/go/src/github.
com/gardener/etcd-wrapper/main.go:58\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
When etcd-druid attempts to update the STS component it first checks if there are changes to TLS configuration. It is a bit conservative and errs on the side of caution by not updating the STS if all pods are not up and ready. So now this pod can no longer be started (without manual intervention) and etcd-druid does not proceed further in reconciling this Etcd resource.

**What you expected to happen**:

etcd-druid should be able to reconcile and update the etcd cluster even if a single pod is down.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy v0.22.x of druid and bring up a 3 member etcd cluster
- Upgrade druid to v0.23.y
- Annotate Etcd resource with `gardener.cloud/operation=reconcile` to force reconciliation of the etcd cluster
- Immediately bring down one of the etcd cluster nodes (ensuring that at least the ConfigMap has been updated but not STS)

**Comment by ishan16696** [comment]
To reproduce this bug, please follow these steps:
1. Deploy etcd-druid with old version `v0.22.x`.
2. Apply Etcd custom resource with peerURL TLS enabled and `.spec.replicas` set to  `3`.
3. Delete one etcd pod member, do not let it come up (here, we uses a validating webhook which stops etcd pod creation).
4. Upgard the etcd-druid with newer version `v0.23.x`.
5. Trigger the etcd reconcile by annotating etcd custom resource 
```
kubectl annotate etcd <etcd-name> -n <namespace> gardener.cloud/operation="reconcile"
```
6. Delete the validating webhook(if you have used one) and let the etcd pod member come-up.
7. Check the logs of etcd container of pod which was down.
