### ISSUE TITLE
Upgrade to golang version 1.23

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-druid#911]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
Upgrade to golang version 1.23.x.

**Why is this needed**:
There were security vulnerabilities reported for v1.22 and we have already moved to 1.23.x in `etcd-backup-restore` and `etcd-wrapper`

**Comment by renormalize** [comment]
#913 reached master but did not get closed automatically. Closing this since the version has been upgraded.
