### ISSUE TITLE
[Feature] Unit tests for etcd-druid reconciliation cycle

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#97]
**Feature (What you would like to be added):**
Unit tests for etcd-druid reconciliation cycle.

**Motivation (Why is this needed?):**
We should have both positive and negative scenarios covered in the unit tests to improve our own productivity and to avoid regression.

**Approach/Hint to the implement solution (optional):**
Replace the kubebuilder way of tests (running `kube-apiserver` and `etcd`) with mock APIs.

**Comment by abdasgupta** [comment]
We added lots of unit tests after this issue is raised
